### ISSUE TITLE
new firebase.auth.TwitterAuthProvider();

### ISSUE THREAD

**Issue by MatthewPringle** [mikkopaderes/ember-firebase-service#15]
Thanks for this service, I have just started looking into it.

I am wondering how I can go about accessing functionality like

new firebase.auth.TwitterAuthProvider();

I can access the global firebase module, but I would rather do it within the service if possible?

**Comment by mikkopaderes** [comment]
It's not possible as the service is the direct representation of [firebase.app.App](https://firebase.google.com/docs/reference/js/firebase.app.App.html).

**Comment by DavidPhilip** [comment]
Does this mean you have to import firebase via auto-import in order to use these AuthProviders? If yes, this isn't practical in terms of payload for these use-cases, right?

**Comment by mikkopaderes** [comment]
> Does this mean you have to import firebase via auto-import in order to use these AuthProviders? If yes, this isn't practical in terms of payload for these use-cases, right?

Not via autoimport, but instead you have to bundle firebase-auth in your ember-cli-build.js as indicated in the README. Then you would need to do:

```javascript
import firebase from 'firebase/app';

const foo = new firebase.auth.TwitterAuthProvider();
```

I don't quite understand what you mean that it's not practical. There's really no going around it, you have to include firebase-auth in your builds in order for it to be sideloaded in your firebase instance.

**Comment by DavidPhilip** [comment]
> I don't quite understand what you mean that it's not practical. There's really no going around it, you have to include firebase-auth in your builds in order for it to be sideloaded in your firebase instance.

I think I misunderstood how it works then, thanks for explaining again 🙏
