### ISSUE TITLE
Cannot read property 'arrayUnion' of undefined

### ISSUE THREAD

**Issue by edukun** [mikkopaderes/ember-firebase-service#22]
I'm trying to use the arrayUnion function of firestore, but it says that FieldValue is undefined.

firebase: service()
...
this.get('firebase').firestore.FieldValue.arrayUnion(...)

I have ember-firebase-service 6.0.4 and firebase 7.7.0

**Comment by mikkopaderes** [comment]
I don't think that API is available in the firebase service which represents [`firebase.app.App](https://firebase.google.com/docs/reference/js/firebase.app). Try this:

```javascript
import firebase from 'firebase';

firebase.FieldValue.arrayUnion(...);
```

**Comment by edukun** [comment]
Now it shows me this error: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp()
If I call firebase.initializeApp(), then says that API key is invalid

**Comment by edukun** [comment]
Could firestore be imported directly? this is the class I need to access [https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore](url)

**Comment by mikkopaderes** [comment]
Sorry about that it should be `firebase.firestore.FieldValue.arrayUnion(...)`.

And yeah, you can import `firebase` directly for use-cases where you need the API for [`firebase`](https://firebase.google.com/docs/reference/js/firebase).

**Comment by edukun** [comment]
Ok, solved. Just needed to call `firebase.firestore.FieldValue.arrayUnion(...)` instead of `this.get('firebase')`
